### ISSUE TITLE
Feature/Support: Migrate route configuration from yaml to annotation/attribute

### ISSUE THREAD

**Issue by malteschlueter** [rectorphp/rector-symfony#168]
# Feature Request

I'm actually working on a legacy application with Symfony 3.4 and everything is structured in not necessary bundles. Actually the ~500 routes of the application are configured with YAML in the different bundles. My target is to migrate the route configuration to annotations or attributes. For the beginning I prefer annotations because there are already Rector rules which converts routes between annotations and attributes and legacy applications may not use PHP 8^^

I've already seen that somebody asked for this feature but no one has implemented it or not?

My first step was to get the resolved routes from Symfony because of the bundle structure a route configuration in YAML for a controller/action looks like `FooBundle:Bar:baz` and will be resolved by the router to `\FooBar\FooBundle\Controller\Bar::bazAction` which makes me easily to get the correct controller and especially the action because inside the Controller there are often more than one action implemented. For testing I implemented a Symfony command which iterates through the existing routes from the Symfony router and every information of route like path, name, default, ... are available. Very easy to get the important information.

Now the PHP files must be edited which will be easy with Rector but I don't know if it possible to iterate over the configured routes instead of iterating over directories/files?

If it's not possible maybe it's possible to extend the Symfony command which I used for testing that it can use Rector to edit the PHP files but the isn't my prefered solution because it wouldn't be a contribution to the Rector project but I publish it on GitHub.

WDYT?
I'm very open for any input :) 
 
## Diff 

```diff
-foo_baz:
-    path: /foo/{baz}
-    defaults: { _controller: FooBundle:Bar:baz, _format: json }
-    methods: [ GET, POST ]

+/**
+ * @Route(name="foo_baz", path="/foo/{baz}", methods={"GET","POST"}, defaults={_format="json"})
+ */
public function bazAction(string $baz)
```

**Comment by TomasVotruba** [comment]
Hi, I needed this 2 weeks ago :)

I'd love to see such feature here. I see 2 challanges that needs to be solved:

* provide a path to routing, e.g. via parameter in `$rector->parameters()`
* mapping `FooBundle:Bar:baz` to exact `bazAction()` method

If you solve these 2, we have a great new rule :+1:

**Comment by malteschlueter** [comment]
Does Rector has access to the Symfony container of the application?
I've seen https://github.com/rectorphp/rector-symfony/blob/main/src/ApplicationMetadata/ListenerServiceDefinitionProvider.php but I don't really see through :D

**Comment by TomasVotruba** [comment]
Running your application container would crash static analysis create unexpected behavior.

So no. But... you can get to container services via Symfony XML config: https://github.com/rectorphp/rector-symfony/blob/main/src/DataProvider/ServiceMapProvider.php

Not sure if something similar is there for routes. Another way would be parsing the YAML file with routes.

**Comment by malteschlueter** [comment]
I have made a lot of progress and I am confident that I will find a workable solution.

But it will take some time until we can integrate it officially into Rector. Tests will take the most of the time I think^^

It works so far, but the PHPDoc is not generated correctly yet. For example, arrays are not enclosed with `{}` and no quotes are written for strings. For the creation of the PHPDoc I use the `SymfonyRouteTagValueNodeFactory`.

**Comment by malteschlueter** [comment]
I've wrapped an array with the `CurlyListNode`. Now it's enclosed with `{}`. But the quotes still missing^^

**Comment by TomasVotruba** [comment]
Hey, that's great news! :clap: 

If you share a PR with code, I'll see what is missing. Unless you discover it sooner :)

**Comment by malteschlueter** [comment]
Hope I've missed nothing :D

**Comment by malteschlueter** [comment]
The first version and a bugfix is already merged. Great thanks to @TomasVotruba for your help :)

There a 2 issues/bugs left. I'm happy for your input people.

The first issue is that the [command](https://github.com/rectorphp/rector/blob/main/vendor/rector/rector-symfony/src/Command/RectorRoutesExportCommand.php#L14) to export the existing routes to a json file is not working without manual changes. The symfony classes has been prefixed and Symfony requires that a command extends from `\Symfony\Component\Console\Command\Command` and it dislikes the prefixed class and crashes.

Is there any way to prevent this or do you've any ideas how we can improve this? @TomasVotruba had the idea following idea https://github.com/rectorphp/rector-symfony/pull/169#discussion_r872453700 but unfortunately I can not get this to work. But maybe someone else?

---

The third issue is that the arrays will not be added to a annotation correctly because the code was converted false. It removed the `array_map` completly instead refactor it as a foreach or something else. My idea is to refactor the original code to a `foreach`.

WDYT?
What library is used for converting the code? Maybe we should open an issue for it.

Original-Code: https://github.com/rectorphp/rector-symfony/blob/main/src/Rector/ClassMethod/AddRouteAnnotationRector.php#L75-L82
Converted-Code: https://github.com/rectorphp/rector/blob/main/vendor/rector/rector-symfony/src/Rector/ClassMethod/AddRouteAnnotationRector.php#L68-L77

**Comment by TomasVotruba** [comment]
Hi @malteschlueter , 
I'm looking into this one this weekend :)

I don't understand which issue is fixed and which needs to be solved. Could you narrow it down for me?  Thank you

**Comment by TomasVotruba** [comment]
This should make the project routing accessible: https://github.com/rectorphp/rector-src/pull/2339
I though we already merged it, but we didn't.

**Comment by TomasVotruba** [comment]
Next piece of puzzle :earth_africa: 

https://github.com/rectorphp/rector-symfony/pull/172

**Comment by TomasVotruba** [comment]
Good news :partying_face: :partying_face: :balloon: 

I've just managed to dump service from a Symfony 2.8, using Rector command :+1: 

![Peek 2022-05-21 14-53](https://user-images.githubusercontent.com/924196/169652367-53618397-0caa-4a36-82c2-dd6a6cebcdb1.gif)

**Comment by malteschlueter** [comment]
Nice work @TomasVotruba! Thanks a lot :)

I've updated the test project and got the following error message. Do I've to reconfigure something inside the Symfony application?

<img width="1664" alt="grafik" src="https://user-images.githubusercontent.com/13586874/169780887-9c00f2ff-24fd-47c9-9c33-94a06afd6b52.png">

**Comment by TomasVotruba** [comment]
I had the same bug almost whole weekend :) that means the container is created without kernel.
Make sure the kernel creates the container, not just the cached file.

See the 2nd item here: https://github.com/rectorphp/rector-symfony#configuration

**Comment by trsteel88** [comment]
@TomasVotruba, I can't get the AddRouteAnnotationRector to work. I think the documentation is incomplete or incorrect.

Firstly, shouldn't the tests/symfony-container.php actually be:

```php
<?php

use App\Kernel;

require __DIR__.'/../vendor/autoload.php';

$appKernel = new Kernel('tests', false);
$appKernel->boot();

return $appKernel->getContainer();
```

The example uses AppKernel and is missing the use + require etc.

Finally, once I use the above config I see the following error.

```
> rector process
PHP Fatal error:  Uncaught TypeError: RectorPrefix20220523\Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator::__construct(): Argument #1 ($container) must be of type RectorPrefix20220523\Symfony\Component\DependencyInjection\ContainerBuilder, Symfony\Component\DependencyInjection\ContainerBuilder given, called in vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php on line 187 and defined in vendor/rector/rector/vendor/symfony/dependency-injection/Loader/Configurator/ContainerConfigurator.php:52
Stack trace:
#0 vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php(187): RectorPrefix20220523\Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator->__construct(Object(Symfony\Component\DependencyInjection\ContainerBuilder), Object(Symfony\Component\DependencyInjection\Loader\PhpFileLoader), Array, '/usr/local/var/...', '/usr/local/var/...', 'tests')
#1 vendor/symfony/dependency-injection/Loader/ClosureLoader.php(39): App\Kernel->Symfony\Bundle\FrameworkBundle\Kernel\{closure}(Object(Symfony\Component\DependencyInjection\ContainerBuilder), 'tests')
#2 vendor/symfony/config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\ClosureLoader->load(Object(Closure), NULL)
#3 vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php(195): Symfony\Component\Config\Loader\DelegatingLoader->load(Object(Closure))
#4 vendor/symfony/http-kernel/Kernel.php(636): App\Kernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader))
#5 vendor/symfony/http-kernel/Kernel.php(537): Symfony\Component\HttpKernel\Kernel->buildContainer()
#6 vendor/symfony/http-kernel/Kernel.php(767): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#7 vendor/symfony/http-kernel/Kernel.php(128): Symfony\Component\HttpKernel\Kernel->preBoot()
#8 src/Kernel.php(22): Symfony\Component\HttpKernel\Kernel->boot()
#9 tests/symfony-container.php(14): App\Kernel->boot()
#10 vendor/rector/rector/vendor/rector/rector-symfony/src/Bridge/Symfony/ContainerServiceProvider.php(24): require_once('/usr/local/var/...')
#11 vendor/rector/rector/vendor/rector/rector-symfony/src/Bridge/Symfony/Routing/SymfonyRoutesProvider.php(34): Rector\Symfony\Bridge\Symfony\ContainerServiceProvider->provideByName('router')
#12 vendor/rector/rector/vendor/rector/rector-symfony/src/Rector/ClassMethod/AddRouteAnnotationRector.php(57): Rector\Symfony\Bridge\Symfony\Routing\SymfonyRoutesProvider->provide()
#13 vendor/rector/rector/src/Rector/AbstractRector.php(221): Rector\Symfony\Rector\ClassMethod\AddRouteAnnotationRector->refactor(Object(PhpParser\Node\Stmt\ClassMethod))
#14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
#15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#17 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#18 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#19 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#20 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42): PhpParser\NodeTraverser->traverse(Array)
#21 vendor/rector/rector/src/Application/FileProcessor.php(61): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#22 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(126): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#23 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(93): Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#24 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(176): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#25 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(148): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#26 vendor/rector/rector/src/Console/Command/ProcessCommand.php(129): Rector\Core\Application\ApplicationFileProcessor->run(Object(Rector\Core\ValueObject\Configuration), Object(RectorPrefix20220523\Symfony\Component\Console\Input\ArgvInput))
#27 vendor/rector/rector/vendor/symfony/console/Command/Command.php(282): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20220523\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220523\Symfony\Component\Console\Output\ConsoleOutput))
#28 vendor/rector/rector/vendor/symfony/console/Application.php(861): RectorPrefix20220523\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20220523\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220523\Symfony\Component\Console\Output\ConsoleOutput))
#29 vendor/rector/rector/vendor/symfony/console/Application.php(289): RectorPrefix20220523\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20220523\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220523\Symfony\Component\Console\Output\ConsoleOutput))
#30 vendor/rector/rector/src/Console/ConsoleApplication.php(66): RectorPrefix20220523\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20220523\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220523\Symfony\Component\Console\Output\ConsoleOutput))
#31 vendor/rector/rector/vendor/symfony/console/Application.php(187): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20220523\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220523\Symfony\Component\Console\Output\ConsoleOutput))
#32 vendor/rector/rector/bin/rector.php(129): RectorPrefix20220523\Symfony\Component\Console\Application->run()
#33 vendor/rector/rector/bin/rector(5): require_once('/usr/local/var/...')
#34 vendor/bin/rector(117): include('/usr/local/var/...')
#35 {main}
thrown in vendor/rector/rector/vendor/symfony/dependency-injection/Loader/Configurator/ContainerConfigurator.php on line 52
Fatal error: Uncaught TypeError: RectorPrefix20220523\Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator::__construct(): Argument #1 ($container) must be of type RectorPrefix20220523\Symfony\Component\DependencyInjection\ContainerBuilder, Symfony\Component\DependencyInjection\ContainerBuilder given, called in vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php on line 187 and defined in vendor/rector/rector/vendor/symfony/dependency-injection/Loader/Configurator/ContainerConfigurator.php:52
Stack trace:
#0 vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php(187): RectorPrefix20220523\Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator->__construct(Object(Symfony\Component\DependencyInjection\ContainerBuilder), Object(Symfony\Component\DependencyInjection\Loader\PhpFileLoader), Array, '/usr/local/var/...', '/usr/local/var/...', 'tests')
#1 vendor/symfony/dependency-injection/Loader/ClosureLoader.php(39): App\Kernel->Symfony\Bundle\FrameworkBundle\Kernel\{closure}(Object(Symfony\Component\DependencyInjection\ContainerBuilder), 'tests')
#2 vendor/symfony/config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\ClosureLoader->load(Object(Closure), NULL)
#3 vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php(195): Symfony\Component\Config\Loader\DelegatingLoader->load(Object(Closure))
#4 vendor/symfony/http-kernel/Kernel.php(636): App\Kernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader))
#5 vendor/symfony/http-kernel/Kernel.php(537): Symfony\Component\HttpKernel\Kernel->buildContainer()
#6 vendor/symfony/http-kernel/Kernel.php(767): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#7 vendor/symfony/http-kernel/Kernel.php(128): Symfony\Component\HttpKernel\Kernel->preBoot()
#8 src/Kernel.php(22): Symfony\Component\HttpKernel\Kernel->boot()
#9 tests/symfony-container.php(14): App\Kernel->boot()
#10 vendor/rector/rector/vendor/rector/rector-symfony/src/Bridge/Symfony/ContainerServiceProvider.php(24): require_once('/usr/local/var/...')
#11 vendor/rector/rector/vendor/rector/rector-symfony/src/Bridge/Symfony/Routing/SymfonyRoutesProvider.php(34): Rector\Symfony\Bridge\Symfony\ContainerServiceProvider->provideByName('router')
#12 vendor/rector/rector/vendor/rector/rector-symfony/src/Rector/ClassMethod/AddRouteAnnotationRector.php(57): Rector\Symfony\Bridge\Symfony\Routing\SymfonyRoutesProvider->provide()
#13 vendor/rector/rector/src/Rector/AbstractRector.php(221): Rector\Symfony\Rector\ClassMethod\AddRouteAnnotationRector->refactor(Object(PhpParser\Node\Stmt\ClassMethod))
#14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
#15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#17 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#18 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#19 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#20 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42): PhpParser\NodeTraverser->traverse(Array)
#21 vendor/rector/rector/src/Application/FileProcessor.php(61): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#22 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(126): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#23 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(93): Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#24 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(176): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#25 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(148): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#26 vendor/rector/rector/src/Console/Command/ProcessCommand.php(129): Rector\Core\Application\ApplicationFileProcessor->run(Object(Rector\Core\ValueObject\Configuration), Object(RectorPrefix20220523\Symfony\Component\Console\Input\ArgvInput))
#27 vendor/rector/rector/vendor/symfony/console/Command/Command.php(282): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20220523\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220523\Symfony\Component\Console\Output\ConsoleOutput))
#28 vendor/rector/rector/vendor/symfony/console/Application.php(861): RectorPrefix20220523\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20220523\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220523\Symfony\Component\Console\Output\ConsoleOutput))
#29 vendor/rector/rector/vendor/symfony/console/Application.php(289): RectorPrefix20220523\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20220523\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220523\Symfony\Component\Console\Output\ConsoleOutput))
#30 vendor/rector/rector/src/Console/ConsoleApplication.php(66): RectorPrefix20220523\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20220523\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220523\Symfony\Component\Console\Output\ConsoleOutput))
#31 vendor/rector/rector/vendor/symfony/console/Application.php(187): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20220523\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220523\Symfony\Component\Console\Output\ConsoleOutput))
#32 vendor/rector/rector/bin/rector.php(129): RectorPrefix20220523\Symfony\Component\Console\Application->run()
#33 vendor/rector/rector/bin/rector(5): require_once('/usr/local/var/...')
#34 vendor/bin/rector(117): include('/usr/local/var/...')
#35 {main}
thrown in vendor/rector/rector/vendor/symfony/dependency-injection/Loader/Configurator/ContainerConfigurator.php on line 52
```

**Comment by TomasVotruba** [comment]
@trsteel88 The classes must be FQN of your exact project. The README contains example.
The autoload is already included in Rector, so need to autoload twice. Rector should be part of project in `require-dev`, like e.g. PHPUnit.

I have a theory about race condition in autoload, but we'll need minirmal reproducer.

**Comment by TomasVotruba** [comment]
Closing as feature is added and confirmed :+1: 

Thanks @malteschlueter for great work :clap:

**Comment by trsteel88** [comment]
> @trsteel88 The classes must be FQN of your exact project. The README contains example. The autoload is already included in Rector, so need to autoload twice. Rector should be part of project in `require-dev`, like e.g. PHPUnit.
> 
> I have a theory about race condition in autoload, but we'll need minirmal reproducer repository.

Yes I have it included in the project through dev dependencies and still didn't have any luck (even with the template provided). Do you have a working example by any chance?

**Comment by TomasVotruba** [comment]
Nothing except tests. We'll need reproducible repository.

**Comment by malteschlueter** [comment]
@trsteel88 In my example project it works well maybe it will help https://github.com/malteschlueter/symfony-reproducers/tree/feature/rector-add-route-annotation
