### ISSUE TITLE
[SYMFONFY33] ArgumentAdderRector is configured incorrectly

### ISSUE THREAD

**Issue by Tiefschwarz** [rectorphp/rector-symfony#327]
# Bug Report

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/fec44916-df27-4cd0-ab29-f8422142516f (I copied the rector configuration from the `config/sets/symfony/symfony33.php` that seems to cause the issue)

```php
<?php

use Symfony\Component\DependencyInjection\ContainerBuilder;

final class DemoFile
{
    public function run()
    {
        $container = new ContainerBuilder();
        $container->compile();
    }
}
```

Minimal configuration necessary;

```php
<?php

use Rector\Config\RectorConfig;
use Rector\Symfony\Set\SymfonySetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->sets([
        SymfonySetList::SYMFONY_33,
    ]);
};
```

## Expected Behavior

Rector changes the file to:

```php
<?php

use Symfony\Component\DependencyInjection\ContainerBuilder;

final class DemoFile
{
    public function run()
    {
        $container = new ContainerBuilder();
        $container->compile(false);
    }
}
```

The expected behavior is based on the fact that Symfony throws a deprecation error when the `compile` method is used without an argument.

For reference:

- https://github.com/symfony/symfony/blob/v3.3.18/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L709
- https://github.com/symfony/symfony/blob/v4.0.0/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L684

## Actual Behavior

Rector returns the following error:

```
 "System error: "Previous position does not has default value"

         Stack trace:
         #0 vendor/rector/rector/rules/Arguments/Rector/ClassMethod/ArgumentAdderRector.php(182):
         Rector\Arguments\Rector\ClassMethod\ArgumentAdderRector->fillGapBetweenWithDefaultValue(Object(PhpParser\Node\
         Expr\MethodCall), 2)
         #1 vendor/rector/rector/rules/Arguments/Rector/ClassMethod/ArgumentAdderRector.php(171):
         Rector\Arguments\Rector\ClassMethod\ArgumentAdderRector->processMethodCall(Object(PhpParser\Node\Expr\MethodCa
         ll), 0, 2)
         #2 vendor/rector/rector/rules/Arguments/Rector/ClassMethod/ArgumentAdderRector.php(120):
         Rector\Arguments\Rector\ClassMethod\ArgumentAdderRector->processPositionWithDefaultValues(Object(PhpParser\Nod
         e\Expr\MethodCall), Object(Rector\Arguments\ValueObject\ArgumentAdder))
         #3 vendor/rector/rector/src/Rector/AbstractRector.php(216):
         Rector\Arguments\Rector\ClassMethod\ArgumentAdderRector->refactor(Object(PhpParser\Node\Expr\MethodCall))
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\MethodCall))
         #5 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):
         PhpParser\NodeTraverser->traverseArray(Array)
         #13 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42):
         PhpParser\NodeTraverser->traverse(Array)
         #14 vendor/rector/rector/src/Application/FileProcessor.php(60):
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
         #15 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(100):
         Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration))
         #16 vendor/rector/rector/packages/Parallel/WorkerRunner.php(135):
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\Fil
         e), Object(Rector\Core\ValueObject\Configuration))
         #17 vendor/rector/rector/packages/Parallel/WorkerRunner.php(106):
         Rector\Parallel\WorkerRunner->processFiles(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration), Array)
         #18 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}(Array)
         #19 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):
         RectorPrefix202212\Evenement\EventEmitter->emit('data', Array)
         #20 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         RectorPrefix202212\Clue\React\NDJson\Decoder->handleData(Array)
         #21 vendor/rector/rector/vendor/react/stream/src/Util.php(62):
         RectorPrefix202212\Evenement\EventEmitter->emit('data', Array)
         #22 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         RectorPrefix202212\React\Stream\Util::RectorPrefix202212\React\Stream\{closure}('{"action":"main...')
         #23 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):
         RectorPrefix202212\Evenement\EventEmitter->emit('data', Array)
         #24 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):
         RectorPrefix202212\React\Stream\DuplexResourceStream->handleData(Resource id #3192)
         #25 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):
         RectorPrefix202212\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
         #26 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):
         RectorPrefix202212\React\EventLoop\StreamSelectLoop->run()
         #27 vendor/rector/rector/vendor/symfony/console/Command/Command.php(311):
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202212\Symfony\Component\Console\Input\A
         rgvInput), Object(RectorPrefix202212\Symfony\Component\Console\Output\ConsoleOutput))
         #28 vendor/rector/rector/vendor/symfony/console/Application.php(899):
         RectorPrefix202212\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202212\Symfony\Component\
         Console\Input\ArgvInput), Object(RectorPrefix202212\Symfony\Component\Console\Output\ConsoleOutput))
         #29 vendor/rector/rector/vendor/symfony/console/Application.php(320):
         RectorPrefix202212\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Work
         erCommand), Object(RectorPrefix202212\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202212\Symfony\Component\Console\Output\ConsoleOutput))
         #30 vendor/rector/rector/src/Console/ConsoleApplication.php(49):
         RectorPrefix202212\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202212\Symfony\Component\Co
         nsole\Input\ArgvInput), Object(RectorPrefix202212\Symfony\Component\Console\Output\ConsoleOutput))
         #31 vendor/rector/rector/vendor/symfony/console/Application.php(206):
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202212\Symfony\Component\Console\Input\ArgvIn
         put), Object(RectorPrefix202212\Symfony\Component\Console\Output\ConsoleOutput))
         #32 vendor/rector/rector/bin/rector.php(128): RectorPrefix202212\Symfony\Component\Console\Application->run()
         #33 vendor/rector/rector/bin/rector(4): require_once('ve...')
         #34 bin/rector(115): include('ve...')
         #35 {main}". On line: 205
```

**Comment by johanadivare** [comment]
Fixed with https://github.com/rectorphp/rector-symfony/pull/328 this ticket can be closed

**Comment by TomasVotruba** [comment]
Thanks @johanadivare  :+1:
